steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/fpl-analytics-488811/fpl-analytics-artifacts/fpl-base-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/fpl-analytics-488811/fpl-analytics-artifacts/fpl-base-image']
options:
  logging: CLOUD_LOGGING_ONLY