name: 'fpl_analytics'
version: '1.0.0'

profile: 'fpl_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fpl_analytics:
    staging:
      staging_player:
        +schema: stg_player
        +materialized: view
      staging_fixture:
        +schema: stg_fixture
        +materialized: view

    curated:
      curated_player:
        +schema: curated_player
        +materialized: view
      curated_fixture:
        +schema: curated_fixture
        +materialized: view
      curated_team:
        +schema: curated_team
        +materialized: view

    prod:
      fpl_prod:
        +schema: fpl_prod
        +materialized: view
      +schema: fpl_prod
      +materialized: view
