fpl_analytics:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      threads: 4
      location: europe-west2