version: 2

sources:
  - name: raw_player
    database: fpl-analytics-488811
    schema: raw_player
    tables:
      - name: raw_player_data
      - name: raw_player_stats

  - name: raw_team
    database: fpl-analytics-488811
    schema: raw_team
    tables:
      - name: raw_team_data

  - name: raw_fixture
    database: fpl-analytics-488811
    schema: raw_fixture
    tables:
      - name: raw_fixture_data