version: 2

sources:
  - name: raw_player
    database: fpl-analytics-488811
    schema: raw_player
    tables:
      - name: raw_player_data
      - name: raw_player_stats

  - name: raw_team
    database: fpl-analytics-488811
    schema: raw_team
    tables:
      - name: raw_team_data

  - name: raw_fixture
    database: fpl-analytics-488811
    schema: raw_fixture
    tables:
      - name: raw_fixture_data

  - name: stg_player
    database: fpl-analytics-488811
    schema: stg_player
    tables:
      - name: stg_player_stats
      - name: stg_player_data
      - name: stg_selection_info
    
  - name: stg_fixture
    database: fpl-analytics-488811
    schema: stg_fixture
    tables:
      - name: stg_fixture_data
      - name: stg_fixtures_by_team 

  - name: curated_team
    database: fpl-analytics-488811
    schema: curated_team 
    tables:
      - name: cur_team_taxonomies

  - name: curated_player
    database: fpl-analytics-488811
    schema: curated_player
    tables:
      - name: cur_player_taxonomies
      - name: cur_player_five_gw_stats
      - name: cur_player_ten_gw_stats
      - name: cur_selection_info
      - name: cur_total_stats

  - name: curated_fixture
    database: fpl-analytics-488811
    schema: curated_fixture
    tables:
      - name: cur_next_five_fixtures
      - name: cur_fixtures_by_team
